#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper;
use LWP::UserAgent;

my $freq = undef;
while (my $line = <STDIN>) {
    last if $line =~ m{^[\n\r]+$};
    $freq .= $line;
}

my $fres = undef;
{ local $/; $fres = <STDIN>; }

my $res = HTTP::Response->parse($fres) or
  die "ERROR: parse\n";
$res->is_success or
  die "ERROR: " . $res->status_line . "\n";

print $res->decoded_content;
exit 0;

print $res->request->as_string;
print $res->as_string;
